### ISSUE TITLE
Problem with fonts

### ISSUE THREAD

**Issue by e7rain** [brandonlim-hs/wkhtmltopdf-aws-lambda-layer#1]
I was trying nodejs12.x runtime, I didn't succeed.

wkhtmltopdf does not emit any error the pdf is generated.

But you don't see characters just squares.
I was investigating and it seems that the fonts are missing.

You can try the function here

``
echo "<html><body>Test</body></html>" | http --download POST https://kt7b9gdixh.execute-api.us-east-1.amazonaws.com/dev/converter
``

**Comment by brandonlim-hs** [comment]
nodejs12.x runs on Amazon Linux 2 operating system. Since [Amazon Linux 2](https://aws.amazon.com/amazon-linux-2/) "removes the number of non-critical packages which are installed on an instance", fonts are no longer available by default.
Therefore, we will need to include our own fonts when using Amazon Linux 2.
Please see: 
- https://github.com/brandonlim-hs/wkhtmltopdf-aws-lambda-layer#fonts
- https://github.com/brandonlim-hs/fonts-aws-lambda-layer#usage

Note: my fonts layer currently only include stix-fonts. You can use as reference to add other fonts.
